### PR TITLE
RPC: Resolve promises when preconditions fail

### PR DESCRIPTION
**Pull request by teozkr**
Resolves the hanging part of #327

### CODE REVIEW

**Comment by teozkr** [comment]
This feels like it's indicative of a larger pattern where `Pinky`s are often dropped without resolution in the unhappy paths, leaving the user to hang forever. Most other `Promise` implementations (such as futures' [`oneshot` channels](https://docs.rs/futures/0.3.13/futures/channel/oneshot/index.html)) return some kind of cancellation error in those cases, but `pinky-swear`'s types don't really allow for that.

**Comment by Keruspe** [comment]
there's some rework around this in 2.0 fwiw, which is unfinished yet

**Comment by Keruspe** [comment]
We really shouldn't end up there. The issue is rather in the error_consumers logic

**Comment by Keruspe** [comment]
Thanks for this though, actually makes sense.

I'll see how we can forward the actual error now instead of some "default" one

**Comment by Keruspe** [comment]
Done in 043704fb724d24152cb675808e87f129e2f1d51e

**Pull request merged**
