### PR TITLE
Passthrough the rustls feature

### PR DESCRIPTION
**Pull request by mkpankov**
Signed-off-by: Michael Pankov <work@michaelpankov.com>

### CODE REVIEW

**Comment by mkpankov** [comment]
1.40 is failing, is it mandatory to support it?

**Comment by Keruspe** [comment]
You can just enable it for lapin in your dependencies, can't you?

**Comment by mkpankov** [comment]
No, I'm using `deadpool-lapin`, so I have to pass features through.

**Comment by Keruspe** [comment]
I think you should either declare lapin explicitly with the feature or add
this to deadpool-lapin then

**Comment by mkpankov** [comment]
I'm actually using all three crates (`lapin`, `deadpool-lapin` and `tokio-amqp`). I'm going to check the exact issue, but it didn't work for some reason.

**Comment by mkpankov** [comment]
You're right, it turned out to be not necessary.

For anyone else who stumbles upon this: watch out for `default-features` (which need to be false) and if switching a single dependency to git or path, switch its users too if they're all part of one repository (otherwise two version of the same library will conflict).

**Pull request closed without merging**
