### PR TITLE
Infinite Loop Fix

### LINKED ISSUE #333: handle unresponsive server
When connecting to un unresponsive server (e.g. docker proxy that didn't yet kill the connection on server restart) lapin goes on an infinite loop 

Code example:
```
use lapin::{Connection, ConnectionProperties};
use tokio_amqp::*;

const AMQP_URL : &str = "amqp://foo:bar@localhost:4242//";

#[tokio::main]
async fn main() {
    env_logger::init();
    println!("Hello, world!");
    log::debug!("bootstrap amqp");
    let conn = Connection::connect(AMQP_URL, ConnectionProperties::default().with_tokio()).await.unwrap();
    log::debug!("established amqp connection");
    let channel = conn.create_channel().await.unwrap();
    log::debug!("created amqp channel");
}
```
then open a connection with `nc -l -p 4242`, if you drop the connection with ctrl-d before sending the first Byte, lapin goes on an infinite loop of 
```
[2021-04-26T14:15:26Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
[2021-04-26T14:15:26Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
[2021-04-26T14:15:26Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
[2021-04-26T14:15:26Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
[2021-04-26T14:15:26Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
[2021-04-26T14:15:26Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
[2021-04-26T14:15:26Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
[2021-04-26T14:15:26Z ERROR lapin::io_loop] Socket was readable but we read 0, marking as wouldblock
```

### PR DESCRIPTION
**Pull request by dbcfd**
Fixes #333 by separating connection close from buffer being full.

### CODE REVIEW

**Comment by Keruspe** [comment]
Any chance you can do this in the lapin-1.x branch instead?

**Comment by Keruspe** [comment]
We don't try reading where the buffer is full so the nospace will never happen.

Are you 100% sure a read of 0 on a readable socket means that it is closed ? I'm pretty sure we didn't want to do that for a reason.

Yes it might fix some cases but it might also break some legitimate scenarii.

**Comment by Keruspe** [comment]
WRT your deadlock fix, care to explain how you ended up with a deadlock ? Your change doesn't seem to change anything ?

**Comment by dbcfd** [comment]
> WRT your deadlock fix, care to explain how you ended up with a deadlock ? Your change doesn't seem to change anything ?

My mistake, thought it was calling the locking function on resetting the timeout.

**Comment by Keruspe** [comment]
Thanks anyways, I ended up considering Read(0) as a connection failure in the end, thanks for the pointer

**Pull request closed without merging**
