### PR TITLE
Topology support

### PR DESCRIPTION
**Pull request by Keruspe**
This will allow saving and restoring the topology of a rabbitmq connection

### CODE REVIEW

**Comment by FGRibreau** [comment]
Nice addition :+1:! Will use it 👌

**Comment by Keruspe** [comment]
It's still a draft, I have several changes coming up, but soon you'll be able to create all your channels, queues, bindings, consumers in one step from a json descriptor.

This is all to pave way for clean and reliable automatic reconnection

**Comment by FGRibreau** [comment]
Currently only the topology as output is supported by this PR right? (I double-checked and could not find the topology json as input :D)

**Comment by Keruspe** [comment]
Indeed, I want to finish output before doing input as the last steps for input will require some internal reworks

**Comment by Keruspe** [comment]
Generation TODO:

- [ ] Split consumers from queues both in queues.rs and topology.rs
- [ ] Only store exclusive queues in channels + generated channel-specific queues topology
- [ ] Totally nuke QueueState
- [ ] Ensure we're properly hooked-up for nowait in all the queue/exchange declare/delete/bind/unbind (we're not, at least for excahnges stuff).
- [ ] Force nowait = false in generated topology

**Comment by Keruspe** [comment]
@FGRibreau interested in some feedback wrt this syntax: https://github.com/CleverCloud/lapin/blob/9c1b587e0258fe25ef27ad20a65a7e614934a635/examples/restore-topology.rs#L25-L31

**Comment by FGRibreau** [comment]
Seems good to me :)

**Pull request merged**
