### PR TITLE
Fixed wrong blocking example in case for consumer messages

### PR DESCRIPTION
**Pull request by Emulator000**
The example was blocking and wrong, I corrected it with a correct iteration :-)

### CODE REVIEW

**Comment by Emulator000** [comment]
Also, please, put this repo to be elegible for the Hacktoberfest xD

```Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.```

**Comment by Keruspe** [comment]
Since the master branch is now full async, I guess this makes sense.

You commit doesn't compile though.

**Comment by Emulator000** [comment]
@Keruspe fixed! :-)

**Comment by Keruspe** [comment]
Can you keep imports sorted please?

**Comment by Emulator000** [comment]
@Keruspe what do you mean? I ran "cargo fmt" for the file and it seems fixed now, by the way, in the CI I see a loop error that I think is not related with my changes...

**Comment by Keruspe** [comment]
Nvm, just some pre-coffee morning nonsense.

Will give CI a look

**Pull request merged**
